name          'ivanlei-wireless_tools'
version       '1.0.0'
summary       'Puppet module for wireless tools'
description   'Puppet module for wireless tools'
source        'https://github.com/ivanlei/puppet-wireless_tools.git'
project_page  'https://github.com/ivanlei/puppet-wireless_tools'
license       'http://unlicense.org/'

dependency    'ivanlei/python_tools', '>=1.0.0'
dependency    'ivanlei/hg', '>=1.0.0'
dependency    'puppetlabs/stdlib', '>=4.1.0'
dependency    'puppetlabs/git', '>=0.0.2'
dependency    'puppetlabs/vcsrepo', '>=0.1.2'
dependency    'ivanlei/python_pip', '>=1.0.0'